language: java

dist: xenial

jdk:
# Enable all versions which should be supported
- openjdk8
- openjdk11
# - openjdk13


before_install:
- docker pull elasticsearch:7.9.3
- docker run -d --name elasticsearch4metastore  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.9.3
- sudo apt-get update
- sudo apt-get upgrade --assume-yes
- sudo apt-get install --assume-yes python3 python3-pip 
- pip3 install xmltodict wget

install: true
  
script:
- "./gradlew -Ptravis clean check jacocoTestReport"

after_success:
- "./gradlew coveralls"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
